<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RolePermissionSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */

  private $superAdminPermissions = [
    'view permissions',
    'create permissions',
    'edit permissions',
    'delete permissions',
    'view roles',
    'create roles',
    'edit roles',
    'delete roles',
    'view users',
    'create users',
    'edit users',
    'delete users',
    'view website-home-page',
    'update website-home-page',
    'view website-why-swayam-vidya',
    'update website-why-swayam-vidya',
    'view website-about-us',
    'update website-about-us',
    'view website-contact-us',
    'update website-contact-us',
    'view website-blogs',
    'update website-blogs',
    'view website-become-a-partner',
    'update website-become-a-partner',
    'view website-institutions-and-boards',
    'update website-institutions-and-boards',
    'view website-courses',
    'update website-courses',
    'view website-components',
    'update website-components',
    'view verticals',
    'create verticals',
    'edit verticals',
    'delete verticals',
    'view admission-types',
    'create admission-types',
    'edit admission-types',
    'delete admission-types',
    'view modes',
    'create modes',
    'edit modes',
    'delete modes',
    'view fee-structures',
    'create fee-structures',
    'edit fee-structures',
    'delete fee-structures',
    'view schemes',
    'create schemes',
    'edit schemes',
    'delete schemes',
    'view admission-sessions',
    'create admission-sessions',
    'edit admission-sessions',
    'delete admission-sessions',
    'view eligibility-criteria',
    'create eligibility-criteria',
    'edit eligibility-criteria',
    'delete eligibility-criteria',
    'view student-status',
    'create student-status',
    'edit student-status',
    'delete student-status',
    'view program-types',
    'create program-types',
    'edit program-types',
    'delete program-types',
    'view languages',
    'create languages',
    'edit languages',
    'delete languages',
    'view sources',
    'create sources',
    'edit sources',
    'delete sources',
    'view sub-sources',
    'create sub-sources',
    'edit sub-sources',
    'delete sub-sources',
    'view stages',
    'create stages',
    'edit stages',
    'delete stages',
    'view sub-stages',
    'create sub-stages',
    'edit sub-stages',
    'delete sub-stages',
    'view departments',
    'create departments',
    'edit departments',
    'delete departments',
    'view programs',
    'create programs',
    'edit programs',
    'delete programs',
    'view specializations',
    'create specializations',
    'edit specializations',
    'delete specializations',
    'view leads',
    'create leads',
    'edit leads',
    'delete leads',
    'view students',
    'create students',
    'view custom-fields',
    'edit custom-fields',
    'create custom-fields',
    'delete custom-fields',
    'edit application-form',
    'view application-form',
    'delete application-form',
    'create application-form',
    'edit applications',
    'create applications',
    'view applications',
    'delete applications',
    'view assignment-rules',
    'create assignment-rules',
    'edit assignment-rules',
    'delete assignment-rules',
    'view activities',
    'create activities',
    'edit activities',
    'delete activities',
    'create paper-types',
    'view paper-types',
    'edit paper-types',
    'delete paper-types',
    'view videos',
    'edit videos',
    'create videos',
    'delete videos',
    'create e-books',
    'edit e-books',
    'view e-books',
    'delete e-books',
    'view notes',
    'edit notes',
    'create notes',
    'delete notes',
    'view query-type',
    'edit query-type',
    'create query-type',
    'delete query-type',
    'view query-sub-type',
    'edit query-sub-type',
    'create query-sub-type',
    'delete query-sub-type',
    'approve document',
    'review document',
    'mark-pendency document',
    'edit id-card',
    'delete id-card',
    'create id-card',
    'view id-card',
    're-upload document',
    'view website-career',
    'create website-career',
    'edit website-career',
    'delete website-career',
    'view website-help-center',
    'view vertical-testimonial',
    'create vertical-testimonial',
    'edit vertical-testimonial',
    'delete vertical-testimonial',
    'view offline-payments',
    'create offline-payments',
    'edit offline-payments',
    'delete offline-payments',
    'view wallet-payments',
    'create wallet-payments',
    'edit wallet-payments',
    'delete wallet-payments',
    'view website-help-center-feature',
    'create website-help-center-feature',
    'delete website-help-center-feature',
    'edit website-help-center-feature'
  ];

  private $webSiteManagerPermissions = [
    'view website-home-page',
    'update website-home-page',
    'view website-why-swayam-vidya',
    'update website-why-swayam-vidya',
    'view website-about-us',
    'update website-about-us',
    'view website-contact-us',
    'update website-contact-us',
    'view website-blogs',
    'update website-blogs',
    'view website-become-a-partner',
    'update website-become-a-partner',
    'view website-institutions-and-boards',
    'update website-institutions-and-boards',
    'view website-courses',
    'update website-courses',
    'view website-components',
    'update website-components',
    'view verticals',
    'create verticals',
    'edit verticals',
    'delete verticals',
    'view program-types',
    'create program-types',
    'edit program-types',
    'delete program-types',
    'view departments',
    'create departments',
    'edit departments',
    'delete departments',
    'view programs',
    'create programs',
    'edit programs',
    'delete programs',
    'view specializations',
    'create specializations',
    'edit specializations',
    'delete specializations',
  ];

  public function run(): void
  {
    // Super Admin
    foreach ($this->superAdminPermissions as $permission) {
      Permission::create([
        'name' => $permission,
      ]);
    }
    $role = Role::create(['name' => 'Super Admin']);
    $permissions = Permission::pluck('id', 'id')->all();
    $role->syncPermissions($permissions);

    // Website Manager
    $permissionIds = array();
    $role = Role::create(['name' => 'Website Manager']);
    foreach ($this->webSiteManagerPermissions as $permission) {
      $permission = Permission::where('name', $permission)->first();
      $permissionIds[] = $permission->id;
    }
    $role->syncPermissions($permissionIds);
  }
}
